Fix broken filtered scanning page results pagination buttons
skyportal/skyportal pull request #1002
Opened 2020-09-28 20:57 UTC by acrellin

Closes https://github.com/skyportal/skyportal/issues/933 

This PR fixes a bug where using the pagination buttons on the scanning page would result in the selected filter criteria being ignored in the associated fetch. The next/previous page buttons on the bottom of the page are replaced with a "Back to top :arrow_up:" button.

2020-09-29 18:35 UTC, kmshin1397 approved these changes
LGTM! I like the back to top button idea.

2020-09-29 18:35 UTC, kmshin1397 commented on static/js/components/FilterCandidateList.jsx
> +    console.log("data:", data);
```suggestion
```

2020-09-29 18:38 UTC, acrellin commented on static/js/components/FilterCandidateList.jsx
> +    console.log("data:", data);
Ah yes, of course. Thanks

2020-09-29 18:39 UTC, acrellin commented on static/js/components/FilterCandidateList.jsx
> +    console.log("data:", data);
@kmshin1397 fixed

2020-09-29 22:33 UTC, acrellin commented
None of the GA test failures are related to the scanning page: 
```
FAILED skyportal/tests/frontend/test_observing_planner.py::test_observing_run_skycam_component
FAILED skyportal/tests/frontend/test_source_list.py::test_source_filtering_and_pagination
FAILED skyportal/tests/frontend/test_candidate_page.py::test_public_candidate_page_render
```

2020-09-30 20:22 UTC, dmitryduev requested changes
All looks great to me, but I am sure that there will be people that complain about not having the next/previous page buttons at the bottom of the page. Would it be hard to put them back in please?

2020-09-30 20:23 UTC, dmitryduev approved these changes
Actually, I take it back, let's merge as is, and if there are complaints, will address them (I shouldn't be predicting the future here:).

2020-09-30 20:24 UTC, merged