Correctly coerce inf to infinity
skyportal/skyportal pull request #1153
Opened 2020-10-23 03:32 UTC by stefanv

2020-10-23 03:33 UTC, stefanv commented
@dannygoldstein Any ideas for a test here?

2020-10-23 15:18 UTC, acrellin approved these changes

2020-10-23 17:25 UTC, dannygoldstein commented
@stefanv See proposed changes on https://github.com/stefanv/skyportal/pull/2

2020-10-23 19:46 UTC, dannygoldstein requested changes
See suggested changes on https://github.com/stefanv/skyportal/pull/2

2020-10-23 19:46 UTC, dannygoldstein commented on skyportal/handlers/api/photometry.py
> +                    literal_value = '+infinity'
I think this needs to be string-escaped 
```suggestion
                    literal_value = "'infinity'"
```

2020-10-26 16:51 UTC, stefanv commented
Failures unrelated.

2020-10-26 16:53 UTC, stefanv commented
The content of this patch is now by @dannygoldstein, and @acrellin has approved, so I will go ahead and merge (failures are unrelated).

2020-10-26 16:53 UTC, merged