Track whether a telescope is space based or ground based
skyportal/skyportal pull request #1377
Opened 2020-11-17 22:45 UTC by dannygoldstein

This PR keeps track of whether a given telescope is space based or ground based. If it is space based, it does not show the telescope's airmass plot on the observability page, partially addressing https://github.com/fritz-marshal/fritz-beta-feedback/issues/29.

2020-11-17 22:50 UTC, profjsb requested changes
Not to be nickpicky but...I think it's better to have the attribute be something like `fixed_location` (default True) instead of `space_based`: could imagine non-stationary observer which is not groundbased nor spacebased (ie. Sofia).

2020-11-17 23:25 UTC, dannygoldstein commented
@profjsb fixed

2020-11-18 00:36 UTC, dannygoldstein commented
Looks like there are some CI issues here ...

2020-11-24 20:04 UTC, profjsb approved these changes

2020-11-24 20:04 UTC, merged