Use new connection for each email
skyportal/skyportal pull request #1385
Opened 2020-11-18 21:35 UTC by acrellin

2020-11-18 22:01 UTC, kmshin1397 approved these changes

2020-11-18 22:01 UTC, kmshin1397 commented
waiting on CI to merge

2020-11-18 22:38 UTC, dannygoldstein approved these changes

2020-11-18 23:21 UTC, kmshin1397 commented
@acrellin We need to make sure to call `send_email` only when `len(recipients) > 0` I think? Not sure how the email clients would respond to empty recipients but I assume it would probably throw an error.

2020-11-18 23:31 UTC, kmshin1397 approved these changes

2020-11-19 00:19 UTC, acrellin commented
@kmshin1397 looks like the email notification test is failing on both Travis and GA

2020-11-19 00:19 UTC, kmshin1397 requested changes

2020-11-19 00:19 UTC, kmshin1397 commented on skyportal/tests/frontend/test_sources.py
> +    driver.wait_for_xpath("//*[text()[contains(., 'Invalid email service')]]")
```suggestion
    driver.wait_for_xpath("//*[text()='Notification queued up sucessfully']")
```

2020-11-19 00:20 UTC, kmshin1397 commented
@acrellin Yeah just realized that since we now catch the empty recipients the test should expect a success notification. The change I suggest above should fix it

2020-11-19 00:29 UTC, kmshin1397 approved these changes

2020-11-19 01:31 UTC, kmshin1397 commented
green check on GA yay

2020-11-19 01:39 UTC, dannygoldstein approved these changes

2020-11-19 01:40 UTC, merged