Expand new features documentation
skyportal/skyportal pull request #1516
Opened 2020-12-18 03:32 UTC by acrellin

Closes https://github.com/skyportal/skyportal/issues/1455

2020-12-23 20:32 UTC, dannygoldstein approved these changes

2020-12-23 20:33 UTC, dannygoldstein commented
Excellent ! Thanks @acrellin for this important work

2021-01-05 02:27 UTC, scizen9 requested changes
- Need to update the File creation/edit bookkeeping section to reflect new example (still has RandomString refs).
- Perhaps should remove degeneracy of test name for example: call it 'test_test_comment.py' instead of 'test_comment.py'?

2021-01-13 19:00 UTC, acrellin commented
@scizen9  Thanks for the feedback -- ready for re-review.

2021-01-14 17:40 UTC, scizen9 approved these changes

2021-01-14 17:42 UTC, merged