Refactor photometry detection threshold nsigma to be configurable
skyportal/skyportal pull request #1533
Opened 2020-12-22 18:43 UTC by kmshin1397

There are multiple places throughout the codebase where some n-sigma value/ signal-to-noise ratio is hard-coded and used to determine whether a photometry point is a detection or not. This PR ties all that to a single value in the configs for consistency/configurability. 

Would particularly appreciate careful review of the inline comments I modified to make sure that they make sense in the scientific sense :)

2020-12-23 20:13 UTC, dannygoldstein requested changes
Heroic work. Thanks.

2020-12-23 20:13 UTC, dannygoldstein commented on skyportal/schema.py
> +            fluxerr = nsigflux / data['limiting_mag']
```suggestion
            fluxerr = nsigflux / PHOT_DETECTION_THRESHOLD
```

2020-12-24 08:20 UTC, dmitryduev approved these changes
Thanks @kmshin1397! Feel free to merge once @dannygoldstein's suggestions are in.

2021-01-05 20:16 UTC, kmshin1397 commented
@dannygoldstein Sorry, forgot to come back to this until now. Your suggestion is now implemented

2021-01-09 01:52 UTC, dannygoldstein commented
@kmshin1397 merge conflicts

2021-01-09 02:42 UTC, kmshin1397 commented
@dannygoldstein fixed

2021-01-09 03:36 UTC, merged