User notifications
skyportal/skyportal pull request #1610
Opened 2021-01-21 00:12 UTC by acrellin

This PR implements front-end user notifications and adds a badge next to the profile button that, when clicked, displays all of the user's notifications. They can then be marked read, deleted, or, if applicable, clicked to redirect to the relevant page. 

Users are notified when:
 - they're mentioned in a comment;
 - a group for which they're the first admin member receives a new admission request;
 - they are added to a new group;
 - their group admission request is accepted/declined

Comments are parsed for username tags (containing "@username").

Sample screen captures:
![comment_mention_notification](https://user-images.githubusercontent.com/7230285/105256127-f49b1600-5b39-11eb-8b5d-f1694e7d0776.gif)

![group_admission_request_acceptance_notification](https://user-images.githubusercontent.com/7230285/105256111-f06ef880-5b39-11eb-9e30-79ac558b0a19.png)

![added_to_group_notification](https://user-images.githubusercontent.com/7230285/105256114-f1078f00-5b39-11eb-9b11-22ad4b1b1ab8.png)

![group_admission_request_notification](https://user-images.githubusercontent.com/7230285/105256116-f1078f00-5b39-11eb-8bc2-b99e486b77f7.png)

Closes https://github.com/skyportal/skyportal/issues/1481

2021-01-21 19:17 UTC, acrellin commented
Test failures (2) are now unrelated: 

```
FAILED skyportal/tests/frontend/test_followup_requests.py::test_delete_followup_request_SEDM
FAILED skyportal/tests/frontend/test_sources.py::test_regular_user_cannot_delete_unowned_comment
= 2 failed, 349 passed, 3 xfailed, 1 xpassed, 1 warning, 12 rerun in 2207.54s (0:36:47) =
```

2021-01-22 00:04 UTC, dmitryduev requested changes
Looks really awesome @acrellin! I have a few small requests, all on the UI/UX side.

2021-01-22 00:04 UTC, dmitryduev commented on skyportal/handlers/api/group_admission_request.py
> +                    text=f"{requesting_user.username} has requested to join {group.name}",
[Chips](https://material-ui.com/components/chips/#chip-2)?

2021-01-22 00:04 UTC, dmitryduev commented on skyportal/handlers/api/group_admission_request.py
> +                text=f"Your admission request to group {admission_request.group.name} has been {status}.",
[Chips](https://material-ui.com/components/chips/#chip-2)?

2021-01-22 00:04 UTC, dmitryduev commented on skyportal/tests/frontend/test_notifications.py
> +        f'//*[text()="{user.username} mentioned you in a comment on {public_source.id}"]'
Chips

2021-01-22 00:04 UTC, dmitryduev commented on skyportal/tests/frontend/test_notifications.py
> +        f'//*[text()="{user.username} mentioned you in a comment on {public_source.id}"]'
Chips

2021-01-22 00:08 UTC, acrellin commented on static/js/components/Notifications.jsx
> +          badgeContent={unreadCount}
👍🏼

2021-01-22 00:10 UTC, acrellin commented
@dmitryduev thanks for the review. Regarding styling the message contents w/ Chips, the text is all generated on the Python side. We could possible search for things like "mentioned you", and then split out the author's username, etc, but it'd be a bit of a pain and would easily break if we even slightly change the message format on the back-end.

2021-01-22 00:10 UTC, acrellin commented
@dmitryduev unless you know of a simple, non-hacky way to do that?

2021-01-22 00:17 UTC, acrellin commented on static/js/components/Notifications.jsx
> +        style={{ marginTop: "0.6rem", marginRight: "1rem" }}
Done

2021-01-22 00:17 UTC, dmitryduev commented
@acrellin ah, right, makes sense. Can't think of a clean/easy way... @kmshin1397 can you?

2021-01-22 00:19 UTC, stefanv commented
How about parsing the message and inserting a special Markdown link:

`[@mention](user:id)`

Or something like that.

2021-01-22 00:22 UTC, dmitryduev commented
right @stefanv! we can parse md on the frontend, can we? Backticks would also do then.

2021-01-22 00:24 UTC, stefanv commented
I thought we rendered markdown on the frontend.  If we don't already, it's probably worth adding :)  There are several react components for that.

2021-01-22 00:27 UTC, kmshin1397 commented
Yeah I like Stefan's suggestion of using some special syntax to denote highlighted segments. Maybe we can tag these with URLs so that click on the chips would take you to the group page etc? Like the `[text](url)` markdown link syntax. And just render what's in the brackets as Chip text with a link to `url`. Although we don't really have a useful User page so I guess the username chips wouldn't be all the useful.

2021-01-22 00:32 UTC, acrellin commented
@dmitryduev 

![mark_notifs_read_unread](https://user-images.githubusercontent.com/7230285/105429401-34c7ca80-5c06-11eb-9e5e-52b5b2003000.gif)

2021-01-22 00:33 UTC, acrellin commented
I would like for parsing markdown / styling tags to be added in a later PR. This is the core notifications functionality.

2021-01-22 00:35 UTC, acrellin commented
And I nominate one of you who has a clear idea of how it should be done to tackle that issue ;)

2021-01-22 00:36 UTC, acrellin commented on static/js/components/Notifications.jsx
> +                      Mark read
Done

2021-01-22 00:37 UTC, stefanv commented
I don't think this PR needs that functionality, Ari.  Was just throwing some ideas out there.

2021-01-22 00:41 UTC, acrellin commented
> I don't think this PR needs that functionality, Ari. Was just throwing some ideas out there.

Yeah I think that was clear, thanks, @stefanv :)  I was just making it clear to Dima that he should re-review now and we can add the highlighting stuff later

2021-01-22 00:44 UTC, dmitryduev approved these changes
👍🏻

2021-01-22 00:46 UTC, dmitryduev commented
Markdown parsing definitely should not be part of this PR:)

2021-01-22 00:48 UTC, acrellin commented
Thanks for the review and great feedback, @dmitryduev

2021-01-22 17:03 UTC, kmshin1397 requested changes
Looks good, @acrellin! I would suggest adding tests for the group membership notifications as well. Once that's in place I think this is good to merge.

2021-01-22 18:22 UTC, acrellin commented
@kmshin1397 I've added a test that ensures that both the group admin receives a notification when someone requests admission to a group, and that the requesting user receives a notification when their request has been processed. Ready for re-review

2021-01-22 19:01 UTC, kmshin1397 reviewed
Awesome - sorry, two more minor suggestions

2021-01-22 19:07 UTC, acrellin commented
@kmshin1397 👍🏼 Done

2021-01-22 19:07 UTC, kmshin1397 approved these changes

2021-01-22 19:19 UTC, dmitryduev commented
Can't wait to roll this out! Behold, Slack, Fritz is coming :))

2021-01-22 19:54 UTC, acrellin commented
Failures unrelated

2021-01-22 20:19 UTC, merged