New lines for spectroscopic plots
skyportal/skyportal pull request #1669
Opened 2021-02-15 12:30 UTC by rjoebruch

An updated list of lines compiled by Weizmann, includes now forbidden lines (O II, O III, Ca II), typical WR lines and typical Galaxy lines.

The modification touches only the python file (plot.py)

2021-02-19 00:48 UTC, dmitryduev requested changes
Looks good!

2021-02-19 00:48 UTC, dmitryduev commented on package.json
> +    "check-dependencies": "^1.1.0",
Please rm `package.json` from this PR, does not seem like it's necessary.

2021-02-23 06:04 UTC, dannygoldstein commented
@rjoebruch this is failing the linting checks. Take a look at http://skyportal.io/docs/dev.html#pre-commit-hook

for the fix.

2021-02-24 02:59 UTC, dannygoldstein reviewed
needs a fix for linting checks

2021-02-24 10:03 UTC, rjoebruch commented
Hi Danny, 
I saw the PR problems I’ll check it asap. 

Thanks 
--
Rachel 



> On 24 Feb 2021, at 4:59, Danny Goldstein <notifications@github.com> wrote:
> 
> 
> @dannygoldstein commented on this pull request.
> 
> needs a fix for linting checks
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/skyportal/skyportal/pull/1669#pullrequestreview-597020301>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AK2UZAQIA6BDXC6K7ZVDHE3TARTQ5ANCNFSM4XUTNU5A>.
>

2021-03-01 15:31 UTC, rjoebruch commented
Not sure what went wrong here? Checking out

2021-03-08 08:01 UTC, rjoebruch commented
I do not understand this bug, could you let me know what I should run or check? 
Best!

2021-03-08 17:33 UTC, stefanv commented
@rjoebruch Do you mind making a branch on your own fork of SkyPortal, and then making a new pull request with that branch?  That way, we can help you debug by pushing small changes to your branch.  Currently, your branch is living on the SkyPortal main repository.

2021-03-09 00:00 UTC, dannygoldstein commented
@rjoebruch in the two sources tests that are failing (first two) can you change the text searched from "Mg" to "Mg I"

2021-03-11 21:13 UTC, stefanv commented
Please see https://github.com/skyportal/skyportal/pull/1761

2021-03-11 21:13 UTC, closed without merging