Allow listing git logs from multiple projects
skyportal/skyportal pull request #1760
Opened 2021-03-11 09:33 UTC by stefanv

To facilitate this, we now store git logs in JSON files, instead of as
text files.  Each JSON file contains some meta-data about the git log
(where to link PRs and commits to, what the project is called) as well
as the entries to the git log itself.

2021-03-15 21:53 UTC, acrellin approved these changes

2021-03-17 21:19 UTC, dmitryduev approved these changes
👍🏻

2021-03-17 21:20 UTC, dmitryduev requested changes
Failure on CI is relevant, could you please fix the test (`FAIL: skyportal/tests/utils/test_gitlog.py:13 in test_gitlog_parse`)?

2021-03-23 01:04 UTC, profjsb requested changes
Looks good. Small change requested. Also, looks like a test needs fixing.

2021-03-23 01:04 UTC, profjsb commented on skyportal/handlers/api/sysinfo.py
> +        print(parsed_log)
Remove
```suggestion
```

2021-03-25 23:11 UTC, stefanv commented
Thanks, should be good now.

2021-03-25 23:52 UTC, merged