Replaced loading messages with material ui circularProgress spinners
skyportal/skyportal pull request #2421
Opened 2021-11-12 18:48 UTC by bparazin

![image](https://user-images.githubusercontent.com/56836732/141519002-a71c88e4-9594-40bd-81a4-7f0930d0971a.png)

Taking screenshots is a little tricky since they load really pretty fast

Addresses 2343

2021-11-12 20:21 UTC, acrellin commented
@bparazin Looks like a good start, thanks! I see the following additional files all have loading messages that need to be replaced with spinners:
static/js/components/AirmassPlot.jsx
static/js/components/AssignmentForm.jsx
static/js/components/FollowupRequestForm.jsx
static/js/components/Groups.jsx
static/js/components/ManageDataForm.jsx
static/js/components/NonMemberGroupList.jsx
static/js/components/Observability.jsx
static/js/components/PhotometryTable.jsx
static/js/components/RecentSources.jsx
static/js/components/RunSummary.jsx
static/js/components/SourceDesktop.jsx
static/js/components/SourceMobile.jsx
static/js/components/SourceQuickView.jsx
static/js/components/SourceTable.jsx
static/js/components/UploadPhotometry.jsx
static/js/components/UploadSpectrum.jsx
static/js/components/UserInfo.jsx

2021-11-15 18:27 UTC, bparazin commented
Ah thank you! I only checked for <b>Loading... </b>, so I missed those! On it in 1 sec

2021-11-15 19:17 UTC, bparazin commented
Ok @acrellin that should be all of them?

2021-11-16 16:20 UTC, bparazin commented
Ack, let me fix this test

2021-11-16 16:31 UTC, bparazin commented
??? The test is passing every time on my machine ???

2021-11-16 16:32 UTC, bparazin commented
![image](https://user-images.githubusercontent.com/56836732/142026051-6548042e-32f8-4ce4-b0a8-18f980b8f7d5.png)

2021-11-16 20:55 UTC, acrellin requested changes
Looks good! Just one request below -- removing unnecessary whitespace. Thanks!

2021-11-16 20:55 UTC, acrellin commented on static/js/components/ManageDataForm.jsx
> +                  {" "}
```suggestion
```

2021-11-16 20:58 UTC, bparazin commented on static/js/components/ManageDataForm.jsx
> +                  {" "}
Fixed

2021-11-16 21:22 UTC, acrellin approved these changes

2021-11-16 21:23 UTC, acrellin commented
Will merge when green. Thanks @bparazin !

2021-11-16 21:26 UTC, acrellin commented
Sole test failure is unrelated.

2021-11-16 21:27 UTC, merged