Center spinner 2990
skyportal/skyportal pull request #2475
Opened 2021-12-08 23:32 UTC by avngzy

I've centered the spinners in
1) SourceList
2) CandidateList
3) UserInvitations
4) Peridogram
5) UserManagement

For UserManagement I deleted a <Box> because it was causing the spinner not to show up. If I wasn't supposed to do that let me know and I'll revert my changes.

I left FindingChart alone as I think it looks fine the way it currently is, however let me know if it should be changed.

2021-12-08 23:50 UTC, acrellin reviewed
@avngzy Looking good so far, thanks! Can you please factor out the repeated CSS to a separate module to reduce code duplication?

2021-12-08 23:51 UTC, acrellin commented
@avngzy Also it looks like the linter checks are failing. Have you installed the pre-commit hooks in your development environment?

2021-12-10 23:19 UTC, avngzy commented
Just to clarify, is factoring out to a separate module creating a separate css file and importing that css file/module? Also I have not installed pre-commit hooks, will get to it now.

2021-12-11 00:13 UTC, acrellin commented
@avngzy Never mind, fine to leave it as-is rather than factor it out, which in this case doesn't make as much sense as we're using the mui functions.

2021-12-11 01:47 UTC, avngzy commented
git push --set-upstream origin center-spinner-2990

2021-12-11 01:48 UTC, avngzy commented
Alright! For fixing the api_and_utils test, is there a 'right' way for me to go back to my previous commits and apply the pre-commit linters?

2021-12-11 04:58 UTC, avngzy commented
Figured out how to trigger those precommit checks. I'm getting the following errors for ES Lint
`Check Yaml...........................................(no files to check)Skipped
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
prettier.................................................................Passed
ESLint...................................................................Failed
- hook id: ESLint
- exit code: 1


/Users/beediu/Desktop/skyportal/static/js/components/Periodogram.jsx
  115:17  error    Must use destructuring t_data_uf assignment                                                                                                                  react/destructuring-assignment
  443:6   warning  React Hook useEffect has missing dependencies: 'mjdmax', 'mjdmin', 'plotGLS', 'plotdata', and 'plotted'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  683:31  error    JSX props should not use functions                                                                                                                           react/jsx-no-bind`

I never modified any of those parts and was wondering if it was due to my changes that are causing ES lint to complain?

2021-12-15 17:57 UTC, acrellin commented
@avngzy Make sure you have the latest eslint and prettier plugins installed and run them only on the files changed here.

2022-01-12 17:46 UTC, guynir42 commented
@avngzy any updates on this PR?

2022-01-14 19:28 UTC, avngzy commented
Sorry for the delay, I didn't have access to my old machine for the past few weeks. I've been also having trouble setting up Skyportal's dependencies on my newer mac running ARM architecture so I couldn't get any work done. I was wondering if anybody else on the dev team has succesfully set up Skyportal on a mac using ARM architecture and will be willing to guide me as I've spent hours trying to do so but have had no success.

2022-01-14 19:40 UTC, guynir42 commented
@avngzy Maybe worth asking on the slack channel?

2022-01-26 23:06 UTC, mcoughlin commented
@guynir42 could you take a look at this one? Failure unrelated.

2022-01-27 21:59 UTC, guynir42 approved these changes
If you've manually gone into all these pages and checked that the spinner looks ok, then I think this is ready to merge.

2022-01-27 21:59 UTC, guynir42 commented on docker.yaml
> +    url: http://localhost:5001
This seems like it is not related to this PR...

2022-01-28 21:20 UTC, stefanv requested changes

2022-01-28 21:20 UTC, stefanv commented on static/js/components/Periodogram.jsx
> +/* eslint-disable react/destructuring-assignment */
Why is this necessary?

2022-01-28 21:20 UTC, stefanv commented on static/js/components/Periodogram.jsx
> +  test: {
Unused?

2022-01-28 21:20 UTC, stefanv commented on static/js/components/Periodogram.jsx
>                                onChange={handleMultiplierChange}
And this

2022-01-28 21:20 UTC, stefanv commented on static/js/components/CandidateList.jsx
> +  spinner: {
To prevent having to copy the CSS over and over again, factor out the spinner into its own .jsx file with its own CSS.

2022-03-25 16:51 UTC, mcoughlin commented
Closing in favor of: https://github.com/skyportal/skyportal/pull/2774

2022-03-25 16:51 UTC, closed without merging