WIP: PS1 DR2 API access
skyportal/skyportal pull request #2500
Opened 2021-12-29 23:29 UTC by mcoughlin

I basically copied the ATLAS PR (https://github.com/skyportal/skyportal/pull/2498) and modified to be appropriate for Pan-STARRS. Some notes:

(i) sncosmo needed a version bump to get the PS1 filters... I assume it was being pinned down to 2.5 for a reason though?
(ii) I still do not know what to do about the photometry pushing.

2022-02-19 21:50 UTC, mcoughlin commented
@stefanv @profjsb any idea of the magic required to get this migration to work? The crux of it is the sncosmo 2.5->2.7 upgrade..

2022-02-25 04:53 UTC, profjsb requested changes
Looks good. Some unexpected behavior when:

 a) I try to delete the request (`Cannot delete requests on this instrument.`)
 b) when I try to retrieve a second time after I retrieved already (error = `objID`)
 c) when I try to reissue the exact request and then retrieve, I dont get an error saying that it's a duplicate. Not clear if the data additions are rejected by our API.

Double heck to make sure that the source position is in the right coordinates for what PS1 expects...I think default for ZTF is in J2015.5 (Gaia DR2).

2022-02-25 12:28 UTC, mcoughlin commented
@profjsb all good points. The first two behave correctly now. The third I checked and I see all of the points are rejected by the photometry post, but I am not sure what behavior would be better than that. What do you think?
For the last one, PS1 is J2000, so a mismatch here. I see the source offset handler explicitly calls for J2000. How are we dealing with epochs in the app?

2022-03-04 06:06 UTC, profjsb approved these changes

2022-03-04 06:07 UTC, merged