Spectrum plot tweaks
skyportal/skyportal pull request #2569
Opened 2022-01-17 23:56 UTC by guynir42

- Fixed MANAGE DATA button that was hiding the bottom of Bokeh plot.
- Fixed redshift and expansion velocity inputs to accept any accuracy inputs using numeric input widgets.
![Screenshot from 2022-01-17 15-56-23](https://user-images.githubusercontent.com/37179063/149849077-b156ee5e-9578-4b3d-beec-0c1c26d94e19.png)

2022-01-17 23:57 UTC, guynir42 commented
addresses #2563 and #2386

2022-01-21 04:43 UTC, profjsb requested changes
does this entirely close #2563 and #2386?

2022-01-21 04:43 UTC, profjsb commented on skyportal/plot.py
> +    # )
```suggestion

```

2022-01-21 06:19 UTC, guynir42 commented
> does this entirely close #2563 and #2386?

@profjsb I believe so.

2022-01-25 20:00 UTC, merged