Add columns to Instrument table
skyportal/skyportal pull request #2595
Opened 2022-01-27 16:20 UTC by jadalilleboe

Closes #2527 

Adds magnitude and exposure time columns to Instrument table.

2022-01-27 16:26 UTC, mcoughlin commented
To be slightly more generic, I am wondering if perhaps we do something like a json packet that has the possibility of filter, magnitude, characteristic exposure time, as it will depend on the particular filter what those numbers are. Then these could be displayed on the front-end of the planning page when an instrument is chosen. What do you think @profjsb ?

2022-02-09 17:47 UTC, profjsb commented on skyportal/models/instrument.py
> +    mag = sa.Column(sa.Float, nullable=True, doc="Characteristic limiting magnitude")
maybe call this `limiting_mag`?

2022-02-09 17:47 UTC, profjsb commented on alembic/versions/f492e8ed9d84_add_magnitude_and_exposure_time_columns_.py
> +down_revision = '82f5a89fbe59'
will need to update this down revision hash given that there are new migrations.

2022-02-09 17:47 UTC, profjsb commented
Once this is out of Draft mode, please retag me for review.

2022-02-09 17:48 UTC, mcoughlin commented
@jadalilleboe @profjsb Maybe we discuss at stand up on Thursday, but something more generic like a JSON that knows about filters and so on would probably be more future proof.

2022-02-10 15:49 UTC, jadalilleboe commented
@mcoughlin So are you proposing to get rid of the filters, limiting_mag, and exposure_time columns and combine them all into one JSON column?

2022-02-10 15:50 UTC, mcoughlin commented
@jadalilleboe yes (or similar). Can we discuss at stand-up?

2022-02-10 19:29 UTC, profjsb commented
sensitivity_data ?

2022-02-17 01:31 UTC, jadalilleboe commented
@mcoughlin @profjsb ok I think this is ready for review now

2022-02-17 02:19 UTC, profjsb requested changes
Very nice @jadalilleboe -- just a tiny change then good to go.

2022-02-17 02:19 UTC, profjsb commented on skyportal/handlers/api/instrument.py
> +            filters = data.get("filters")
Will want to make sure filters is always a list
```suggestion
            filters = data.get("filters", [])
```

2022-02-17 23:29 UTC, mcoughlin approved these changes
Great @jadalilleboe. Can you confirm the down_revision is up to date? If so, happy to see this merged.

2022-02-18 00:19 UTC, jadalilleboe commented
@mcoughlin yes can confirm it's up to date.

2022-02-18 15:19 UTC, jadalilleboe commented
not anymore, will update later

2022-02-23 04:30 UTC, profjsb requested changes
Looks good. A few more suggestions:
1) try testing when you add sensitivity_data with more than one entry.
2) can you add more sensitivity data to an existing instrument (via PATCH?) or does someone need to delete the entire instrument? I think it's a good idea to allow PATCHing of sensitivity_data. In this respect, it might be better to have `sensitivity_data` be a dict with the key as the (allowed) filter name. 

 ```python
'sensitivity_data': 
                { 'f110w': 
                   {
                    'limiting_magnitude': 20.5,
                    'magsys': 'ab',
                    'exposure_time': 30,
                   }
                }
```
3)  add a bit of info about the expected behaviors/data in the docs?

2022-02-23 04:30 UTC, profjsb commented on alembic/versions/73bc8919f190_create_sensitivity_data_column.py
> +down_revision = 'd6b24747693a'
check this...may have changed.

2022-02-23 04:30 UTC, profjsb commented on skyportal/tests/api/test_instrument.py
> +
check that the error message is what you expect.

2022-03-17 21:59 UTC, mcoughlin commented
@jadalilleboe Closing in favor of:
https://github.com/skyportal/skyportal/pull/2765
where we will apply these in. We can fix any feedback there.

2022-03-17 21:59 UTC, closed without merging