Adding missing packages that broke pycurl
skyportal/skyportal pull request #2831
Opened 2022-04-07 19:20 UTC by Theodlz

Recently, skyportal couldn't get installed properly as pycurl (package installed with pip) was broken. It seems that adding these 2 packages fixed it. I would suggest to the reviewer to make sure they aren't already installed on his distro before trying it so he can compare and verify their necessity.

2022-04-07 19:25 UTC, mcoughlin requested changes
Some comments on Mac vs Linux.

2022-04-07 19:25 UTC, mcoughlin commented on doc/setup.md
> +brew install supervisor nginx postgresql node libcurl4-gnutls-dev libgnutls28-dev
These don't exist on mac, but I haven't had problems locally, so I expect curl headers are already available.

2022-04-07 19:25 UTC, mcoughlin commented on doc/setup.md
> +- libcurl4-gnutls-dev
Since I think this comes up mostly on Linux systems, maybe we just discuss it explicitly in that section?

2022-04-07 20:45 UTC, mcoughlin commented
@Theodlz Can you add a few words before the install noting the extra purpose for the Linux packages? (i.e. to install pycurl)?

2022-04-08 07:56 UTC, Theodlz commented
> @Theodlz Can you add a few words before the install noting the extra purpose for the Linux packages? (i.e. to install pycurl)?

Done ! I'll let you have a look @mcoughlin, tell me what you think of it.

2022-04-08 11:06 UTC, mcoughlin approved these changes
Thanks @Theodlz

2022-04-08 11:07 UTC, merged