Add more photometry logging
skyportal/skyportal pull request #2914
Opened 2022-05-02 17:35 UTC by mcoughlin

This PR adds more logs for photometry.

2022-05-03 02:25 UTC, stefanv approved these changes

2022-05-06 16:37 UTC, profjsb requested changes
Can you add MAX_NUMBER_ROWS to the API doc? Users should know what we're enforcing.

2022-05-06 16:49 UTC, profjsb commented on skyportal/handlers/api/photometry.py
> +        description: Upload photometry. Posting is capped at {MAX_NUMBER_ROWS} for database stability purposes.
Thanks

2022-05-06 16:50 UTC, profjsb approved these changes
Feel free to merge after tests pass.

2022-05-06 17:52 UTC, merged