Reference Flux Handler
skyportal/skyportal pull request #3469
Opened 2022-09-14 20:41 UTC by guynir42

Add a the input/output code for getting reference flux into the photometry table and out of it. 

Also added tests.

2022-09-28 18:25 UTC, guynir42 commented
@profjsb I added a test for the hybrid properties. This is ready for review.

2022-09-29 16:05 UTC, profjsb requested changes
Looks good. Small comments to fix up.

2022-09-29 16:05 UTC, profjsb commented on skyportal/tests/api/test_photometry.py
> +    expected_fluxerr = 0.123 / 2.5 * np.log(10) * expected_flux
This happens to work but I think parentheses would make for a better read:
`0.123*(np.log(10)/2.5)*expected_flux`

2022-09-29 16:05 UTC, profjsb commented on skyportal/tests/api/test_photometry.py
> +    expected_ref_fluxerr = 0.01 / 2.5 * np.log(10) * expected_ref_flux
same as above comment

2022-09-29 16:05 UTC, profjsb commented on skyportal/tests/api/test_photometry.py
> +    expected_ref_fluxerr = 0.02 / 2.5 * np.log(10) * expected_ref_flux
same

2022-09-29 18:34 UTC, guynir42 commented on skyportal/handlers/api/photometry.py
> +        print(f'adding ref and tot fluxes. ref flux is {phot.ref_flux}')
Just left over from debugging.

2022-09-29 20:22 UTC, merged