Telescope map legend
skyportal/skyportal pull request #3689
Opened 2022-11-18 20:27 UTC by lydie10

Hi @Theodlz @mcoughlin
This PR adds a legend to the telescope map. It's one of the features Sarah asked us to add and she confirmed that the labels were what she wanted. 
Thank you for your feedback and suggestions !

2022-11-18 22:38 UTC, mcoughlin approved these changes
Small wording suggestion.

2022-11-18 22:38 UTC, mcoughlin commented on static/js/components/TelescopePageDesktop.jsx
> +        <p> GCN and Networks </p>
Networks and Space-based Instruments

2022-11-19 11:14 UTC, lydie10 commented on static/js/components/TelescopePageDesktop.jsx
> +        <p> GCN and Networks </p>
okay, thanks I changed it

2022-11-20 09:37 UTC, Theodlz requested changes
Hi, @lydie10. I'm happy with the UI. However, the button to display the legend appears in a weird place for me.
![image](https://user-images.githubusercontent.com/49785117/202894999-5c48ebb9-7109-4ab3-9f7a-ae606d56062f.png)

(see, it's in the upper right corner.)

I would expect it to be closer to the map, let's say on the bottom right corner of it, rather than on the upper right of the form.

2022-11-21 21:30 UTC, lydie10 commented
Thanks to @ManonFlt the legend is now on the bottom right corner of the map

![image](https://user-images.githubusercontent.com/115883967/203161854-cb20516b-436e-4112-810d-64883111add1.png)

2022-11-24 13:52 UTC, Theodlz commented
Hi @lydie10, there has been a breaking change in the python requirements that has been fixed a few days ago. Please pull new changes to your branch, so that the github actions can run and I can review your PR.

2022-11-24 13:59 UTC, Theodlz commented
The code looks good. So once the github actions run and the tests pass, I'll give a green check and merge your PR.

2022-11-25 15:10 UTC, merged