Colors in Classifications
skyportal/skyportal pull request #3965
Opened 2023-02-18 17:53 UTC by KodeurFou

hi @mcoughlin with @celiune and @Adiman007 we've worked on this long over due task :point_right: :point_left: . 
It's the PR for the colors in classifications tasks, we added only few classifications in our rejected / comfirmed dictionnaries but we can make another update to the PR that modifies the dictionnaries if you want to add more classifications NOR colors.

2023-02-18 17:55 UTC, mcoughlin commented
@KodeurFou I think these colors / classes need to go in the config. They are very particular to the instance of SkyPortal you are deploying.

2023-02-20 02:08 UTC, Theodlz requested changes
Hi @KodeurFou, I think your last commit belongs to another PR as it differs greatly from the purpose of this one. Please reverse it or simply delete the changes and recommit.

I agree with @mcoughlin, these colors should be configurable somehow. In the config makes sense for a first PR.

2023-02-22 00:21 UTC, profjsb requested changes

2023-02-22 00:21 UTC, profjsb commented on static/js/components/ShowClassification.jsx
> +  const rejected_classes = ["STOP GRANDMA"];
We should not be hard coding anything with GRANDMA here. You can add these via an environment variable in the config OR have these defined in a table.

2023-03-02 12:39 UTC, Adiman007 commented
@KodeurFou you pushed your code on the wrong branch, I think

2023-03-09 16:31 UTC, closed without merging