Issue #4627 Fixed: "Fixing the Resizing of the 'Add a Source' Drag Down on the Dashboard"
skyportal/skyportal pull request #4641
Opened 2023-11-28 01:50 UTC by pronav5000

The 'Add a Source' menu now properly resizes with a scrollbar when the box is shrunk. Here is an image depicting the change:
![image](https://github.com/skyportal/skyportal/assets/45305455/19f378fe-d6f0-4c5b-91b0-c141d7392dae)

ORIGINAL BUG REPORT: https://github.com/skyportal/skyportal/issues/4627

2023-11-29 01:56 UTC, Theodlz commented
please @pronav5000 update your PR's branch so the github actions can run (I just fixed them)

2023-12-01 21:53 UTC, pronav5000 commented
> please @pronav5000 update your PR's branch so the github actions can run (I just fixed them)

submitted another push, does that fix the problem?

2023-12-01 22:01 UTC, mcoughlin commented
@pronav5000 https://github.com/pronav5000/skyportal/tree/main there should be a button that says "sync fork", please do that.

2023-12-02 11:16 UTC, pronav5000 commented
> @pronav5000 https://github.com/pronav5000/skyportal/tree/main there should be a button that says "sync fork", please do that.

I believe I did that, most of the checks are passing now. Anything I need to do to pass the last one?

2023-12-05 19:24 UTC, Theodlz commented
No! Looks good. LGTM

2023-12-05 19:26 UTC, Theodlz requested changes
Please remove that extra file and we're done!

2023-12-05 19:26 UTC, Theodlz commented on nohup.out
> +sudo: apt-mirror: command not found
Oh actually, please remove this file. I suggest not running `git add .` so that doesnt happen next time.

2023-12-05 19:26 UTC, Theodlz commented
@pronav5000 also remove the changes you made to package.json. they are unnecessary

2023-12-11 17:00 UTC, Theodlz commented
@pronav5000

2024-01-16 15:30 UTC, Theodlz commented
Closing as we removed the widget from the dashboard.

2024-01-16 15:30 UTC, closed without merging