WIP Issue MUI table Recurring api
skyportal/skyportal pull request #4841
Opened 2024-03-23 00:22 UTC by theobonzi

This PR enhances the readability of the Recurring API page by integrating an MUI datatable and expanding its width.
#4828

2024-03-23 00:22 UTC, theobonzi commented
@Theodlz

2024-03-25 16:45 UTC, Theodlz commented
@theobonzi minor comment but when you mention the issue on the PR's description, say something like: Solving issue <issue_number>. Simply because issues and PRs are in the same number sequence, so until I click on it I can't tell if you are solving an issue, or re-opening a PR based on an existing one.

2024-03-27 17:58 UTC, Theodlz commented
Unrelated to the review, but when you are ready to have your code reviewed please click on "ready for review" so that it's not a draft anymore, and remove the WIP unless you have code to add

2024-03-27 18:01 UTC, Theodlz requested changes
Very confused here, most of it is just ... commented code??? Make sure to not leave all of that commented stuff when pushing to a PR, unless you need it for later. 

I'm also not sure that all of it should be commented, looks like some of what you removed is actually important.

2024-03-27 18:01 UTC, Theodlz commented on static/js/components/RecurringAPIPage.jsx
> +//   return (
remove commented code unless it's a mistake

2024-03-28 17:23 UTC, Theodlz commented
@theobonzi please rename your PR without the WIP and make it a normal PR (not a draft) when this is ready for review. Otherwise no way for the reviewer to know!

2024-03-28 21:05 UTC, Theodlz approved these changes
LGTM 🚀

2024-03-28 21:06 UTC, merged

2024-03-28 21:07 UTC, Theodlz commented
@just merged your PR @theobonzi! Just one comment for next time, you added "issue" in your PR, which doesn't make much sense. You mention in the description what issue you are solving, but a PR's name is something reflecting the feature you are developing. It's not an issue but a solution!