Automatically publish source when created
skyportal/skyportal pull request #5195
Opened 2024-08-09 22:15 UTC by antoine-le-calloch

- Allow users to select the "automatically_publish" option for a release. When this option is enabled, any new or updated source that enters the same group as that release will be automatically published.
- create tests for the release API
- improve the test for public_source_page API

2024-08-12 15:50 UTC, Theodlz requested changes
I know this might not be ready for review yet, but I gave it a go anyway. Some comments:
- Say my release have groups A and B. If I save to A, then later save to B before any data on the source has changed, I don't think we need to show the "there is already a release with the same ..." message.
- Linked to the issue above, but when there is a release-related error message pushed to the frontend, it doesn't update the source even though it has correctly been saved to the group!
- Same example: say I have a release with groups A and B. I would imagine that once a source is unsaved from A and B, any release that was autogenerated should be removed, or made invisible at least. That makes me think that a flag to track what releases were autogenerated and which were generated manually would be nice.
- I think that in general you can wrap your code that autogenerates/deletes public pages given a list of group ids (to which a source was saved to, and unsaved from) in a method, that you can then call with the `run_async` method from `skyportal/utils/asynchronous.py`. That way the handler to save sources can return safely undisturbed by that addition, and refresh the source page properly.

2024-08-12 19:23 UTC, antoine-le-calloch commented
> I know this might not be ready for review yet, but I gave it a go anyway. Some comments:
> 
>     * Say my release have groups A and B. If I save to A, then later save to B before any data on the source has changed, I don't think we need to show the "there is already a release with the same ..." message.
> 
>     * Linked to the issue above, but when there is a release-related error message pushed to the frontend, it doesn't update the source even though it has correctly been saved to the group!
> 
>     * Same example: say I have a release with groups A and B. I would imagine that once a source is unsaved from A and B, any release that was autogenerated should be removed, or made invisible at least. That makes me think that a flag to track what releases were autogenerated and which were generated manually would be nice.
> 
>     * I think that in general you can wrap your code that autogenerates/deletes public pages given a list of group ids (to which a source was saved to, and unsaved from) in a method, that you can then call with the `run_async` method from `skyportal/utils/asynchronous.py`. That way the handler to save sources can return safely undisturbed by that addition, and refresh the source page properly.

- Wrap the code with 'run_async'. Done ✅ !
- So don't display public page creation error when its automatic. Done ✅ !
- And allow update the source when there is page creation error. Done ✅ !
- Add flag, to track and delete page automatically publish. In process ⏳!

2025-01-20 20:31 UTC, Theodlz requested changes
Hey @antoine-le-calloch. Thanks a lot for the changes and the clean up! I have a few minor comments, please take a look.

2025-01-20 20:31 UTC, Theodlz commented on alembic/versions/d05256bc14ed_automatically_publish_source_when_.py
> +        'publicreleases',
weird that the 2 columns have almost the same name but not really. Please make sure that they are identical if they mean the same thing

2025-01-20 20:31 UTC, Theodlz commented on alembic/versions/d05256bc14ed_automatically_publish_source_when_.py
> +        'publicreleases',
this comment applies to all the files that use these columns

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/public_pages/public_release.py
> +            if not groups:
not sure if this is a git diff issue, but it looks like the `if not groups` is duplicated. 

Also if you have an if -> else, followed by another if, and the else and the second if return the same error, I wonder if this could be reformatted to avoid having the same 2 returns.

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/source.py
> +        if releases is not None and len(releases) > 0:
i don't think it could be None here right? I suppose that the ORM would always return lists. Worth checking to avoid unnecessary if statements

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/source.py
> +        if releases is not None and len(releases) > 0:
you could also imagine to do `if len(releases) == 0 -> return or whatever you need to do because returning` rather than `if len(releases) > 0 -> a ton of logic that needs to be indentated`. I like to follow this "never indent" principle where possible. Just an advice! Not a requirement at all :)

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/source.py
> +        if releases is not None and len(releases) > 0:
the less indentation, the easier to read

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/source_groups.py
> +                anyOf:
ah didn't know you could use an anyOf here, nice!

2025-01-20 20:31 UTC, Theodlz commented on skyportal/handlers/api/source_groups.py
> +                # Delete all this source auto-published pages, link to a release and sharing no groups with this source
i think the sentence sounds a little odd. the comment could be shortened if not removed

2025-02-03 18:48 UTC, Theodlz approved these changes
LGTM! Nice work Antoine. Let's get this merged so we can try it out soon and see if anything needs to change

2025-02-03 18:49 UTC, Theodlz commented
@antoine-le-calloch I just merged main to your branch to see if everything is still fine. When green (or if no related tests fail), I'll go ahead and merge it

2025-02-03 19:57 UTC, Theodlz commented
@antoine-le-calloch there is some conflit with what has been merged on main today (introduced by https://github.com/skyportal/skyportal/pull/5417), please take a look and let me know once resolved, and if it's all green I'll merge it

2025-02-04 23:15 UTC, Theodlz requested changes
One change request regarding the safety of that query, and then let's merge

2025-02-04 23:15 UTC, Theodlz commented on skyportal/handlers/api/public_pages/public_source_page.py
> +    return session.scalar(
could you just wrap that in a try except or something? The query could return None if the source has no phot stats yet. Unlikely but could be a point of failure that we want to avoid.

2025-02-04 23:15 UTC, Theodlz commented on skyportal/handlers/api/public_pages/public_source_page.py
> +        "t0": safe_round(source.get("t0"), 6),
does that safe round behave correctly when there is no t0? Just wondering

2025-02-04 23:20 UTC, antoine-le-calloch commented on skyportal/handlers/api/public_pages/public_source_page.py
> +        "t0": safe_round(source.get("t0"), 6),
Yep, this is why I have create this safe_round function.

2025-02-05 20:20 UTC, Theodlz approved these changes
LGTM!

2025-02-05 20:22 UTC, merged