display precision of galactic coordinates
skyportal/skyportal pull request #863
Opened 2020-09-06 12:01 UTC by guynir42

increased display precision of galactic coordinates in sources/candidates pages. Fixes issue #809

2020-09-08 10:40 UTC, guynir42 commented
Hi @dannygoldstein @acrellin this is a minor bug fix so I can just merge it, but maybe you want to make sure it looks ok...

2020-09-08 15:38 UTC, acrellin approved these changes

2020-09-08 16:43 UTC, dannygoldstein requested changes

2020-09-08 16:43 UTC, dannygoldstein commented on static/js/components/Candidate.jsx
> +        {candidate.gal_lon}, &nbsp;
```suggestion
        {candidate.gal_lon.toFixed(6)}, &nbsp;
```

2020-09-08 16:43 UTC, dannygoldstein commented on static/js/components/Candidate.jsx
> +        {candidate.gal_lat}
```suggestion
        {candidate.gal_lat.toFixed(6)}
```

2020-09-08 16:43 UTC, dannygoldstein commented on static/js/components/Source.jsx
> +        {source.gal_lon}, &nbsp;
```suggestion
        {source.gal_lon.toFixed(6)}, &nbsp;
```

2020-09-08 16:43 UTC, dannygoldstein commented on static/js/components/Source.jsx
> +        {source.gal_lat}
```suggestion
        {source.gal_lat.toFixed(6)}
```

2020-09-10 18:03 UTC, dannygoldstein approved these changes

2020-09-10 18:03 UTC, merged