Re-skin Profile dropdown to use MUI
skyportal/skyportal pull request #884
Opened 2020-09-10 09:52 UTC by dmitryduev

![dropdown](https://user-images.githubusercontent.com/7557205/92714137-a87cd100-f310-11ea-9abc-8be237841e31.gif)

2020-09-11 04:55 UTC, stefanv commented
For color, I suggest `makeStyle` and access the theme for primary, secondary color, etc.

At some point, we should decide what the theme is going to be and configure that, @kmshin1397.  Currently, it's whatever comes out the box :grimacing:

2020-09-11 07:13 UTC, dmitryduev commented
Yea, I am going to do it like that, just haven't finished. Do you actually like the clickable icon? Or do you prefer no icon and clickable avatar + username?

2020-09-18 20:07 UTC, dmitryduev commented
All tests passing locally, green on Travis, failed on GA - marked the corresponding tests flaky.

2020-09-18 20:54 UTC, dmitryduev commented
Travis is green, an unrelated test (`test_delete_token`) known to be flaky failed on GA.

2020-09-18 21:11 UTC, kmshin1397 reviewed
LGTM!

2020-09-18 21:12 UTC, kmshin1397 approved these changes

2020-09-19 00:47 UTC, dmitryduev commented on package.json
> +    "emojilib": "^2.4.0",
Ah, it should not have been here at all, removed the changes.

2020-09-19 00:47 UTC, dmitryduev commented on skyportal/tests/frontend/test_profile.py
> +    # driver.click_xpath('//*[@id="updateProfileButton"]')
Fixed.

2020-09-21 17:11 UTC, profjsb requested changes
Looks like the avatar spills off the screen on mobile -- perhaps need some small viewport logic.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/480799/93798068-e66fd400-fbf1-11ea-8246-9adae2ec4902.png">

The modal should disappear after navigation completes:
![Kapture 2020-09-21 at 10 06 00](https://user-images.githubusercontent.com/480799/93798255-3b134f00-fbf2-11ea-8d2c-74407fd32e09.gif)

2020-09-21 23:23 UTC, dmitryduev commented on package.json
> +    "emojilib": "^2.4.0",
This file was accidentally committed and is now removed from this PR.

2020-09-21 23:29 UTC, dmitryduev commented
@profjsb addressed the second request. As for the first one -- couldn't reproduced -- tried in Chrome, Safari, and Firefox, even tried using a very long title:
![image](https://user-images.githubusercontent.com/7557205/93831355-7419e680-fc27-11ea-9ffa-75c9c7694648.png)

@kmshin1397 would you mind trying to reproduce the first issue?

2020-09-22 00:06 UTC, profjsb approved these changes

2020-09-22 00:07 UTC, merged